export enum QUERY_KEYS {
  SIGN_IN,
  SIGN_UP,
  GET_ME,
  UPDATE_MY_COMPANY,
  LIST_CLIENTS,
  GET_CLIENT_BY_ID,
  CREATE_CLIENT,
  UPDATE_CLIENT,
  LIST_INVOICES,
  GET_INVOICE_BY_ID,
  CREATE_INVOICE,
  UPDATE_INVOICE,
}
