export enum QUERY_KEYS {
  SIGN_IN = 'SIGN_IN',
  SIGN_UP = 'SIGN_UP',
  GET_ME = 'GET_ME',
  UPDATE_MY_COMPANY = 'UPDATE_MY_COMPANY',
  LIST_CLIENTS = 'LIST_CLIENTS',
  GET_CLIENT_BY_ID = 'GET_CLIENT_BY_ID',
  CREATE_CLIENT = 'CREATE_CLIENT',
  UPDATE_CLIENT = 'UPDATE_CLIENT',
  LIST_INVOICES = 'LIST_INVOICES',
  GET_INVOICE_BY_ID = 'GET_INVOICE_BY_ID',
  CREATE_INVOICE = 'CREATE_INVOICE',
  UPDATE_INVOICE = 'UPDATE_INVOICE',
}
